name: Maven Package upon a push

# Triggered when code is pushed to any branch in a repository
on: push

  #on:
  #  schedule:
  #    # * is a special character in YAML so you have to quote this string
  #    - cron:  '0 12 1 * ?'

jobs:
  Update_Relase_POM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #        names: [partner-management-service, registration, khazana, admin-services, resident-services, commons, audit-manager, pre-registration, print, id-authentication, mosip-openid-bridge, id-repository, durian, keymanager, packet-manager]
        names: [audit-manager]
    env:
      working-director: ${{ matrix.names }}

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: mandeepdhiman123/${{ matrix.names }}
          path: ${{ matrix.names }}
          ref: 1.2.0-rc2
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Branch and Env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=1.2.0-rc2" >> $GITHUB_ENV
        

      - name: Update Pom Files
        run: |
          pwd
          for i in "$(find * -name pom.xml -exec readlink -f {} \;)"
          do
            fullpath=$i
            echo "Updating file : $fullpath"
            sed -i 's/1.2.0-rc2-SNAPSHOT/1.2.0-rc2/g' $fullpath
          done    
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          path: "./${{ matrix.names }}"

